version: '3'

services:
  main:
    container_name: adgate-bot
    restart: always
    build:
      context: .
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN:?err}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=${POSTGRES_DB:?err}
      - OPEN_WEATHER_MAP_KEY=${OPEN_WEATHER_MAP_KEY:?err}

  postgres:
    image: postgres:14-alpine
    container_name: adgate-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=${POSTGRES_DB:?err}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
